package app.documents.core.model.exception

data object CloudAccountNotFoundException : CloudNotFoundException()
